name: CI
   
on : 
    push:
      branches: [main]
    pull_request:
      branches:[main]
      
    workflow_diapatch:
    
jobs:
  build: 
    runs-on:ubuntu-latest
  steps:
   - uses:actions/checkout@v3
   - name:this is one line command
     run:demo text...
      
   
   
  
      
 
